### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by bamorgan13** [ray-leun1/ThisCable#2]
### Users
 - [x] Add `joinedServerIds` array in order to know which servers a user is a member of (to display server icons on nav bar)
### Servers
 - [x] Add `joinedChannelIds` array in order to know which channels are in a server (to display only joined channels in nav bar)
### Channels
 - [x] Add `messageIds` array in order to know which posts are in a channel
### Messages
 - [x] Add `timePosted` in order to have timestamps on messages

Not much to change from what I see at this stage! Having the relationship ids in the store (which `servers` a `user` is a member of, `channels` the `user` has access to in a `server`, etc.) can be very helpful when trying to determine which content to render (iterating over the `user's` `joinedServerIds` to create a component for each of those `servers` in the nav bar, etc.), so I suggested some useful relationships that you will most likely need. You may eventually be adding on to what you keep in your store as you run into more development challenges and advanced features, but what you have here looks like a great foundation! Let me know if you have questions or concerns!

**Comment by ray-leun1** [comment]
### users
* `joinedServerIds` array has been added

### servers
* `joinedChannelIds` array has been added

### channels
* `messageIds` array has been added

### messages
* `timePosted` has been added
* `timePosted` formatted like so: string "year-month-day hour-minute-second timezone"
* "2019-09-28 01:35:02 -0700"
* Is this an appropriate format? Or should I go with the created_at datetime format?
___

I considered that perhaps the `joinedChannelIds` and `messageIds` arrays were not necessary due to the foreign keys referring to `servers` and `channels`, but now I think they may be good for easily placing channels/messages in the order they were created, or reordering channels in a list.
The changes have been applied to the Sample State. Besides my question about timePosted, all else should be good. Thanks for your help!!
